// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFqparin_tEytj5hTwRW589UgEbqQeOO8',
    appId: '1:430839867495:web:53eb53de8c898fe20e4cc2',
    messagingSenderId: '430839867495',
    projectId: 'push-notifications-v1-dec26',
    authDomain: 'push-notifications-v1-dec26.firebaseapp.com',
    storageBucket: 'push-notifications-v1-dec26.appspot.com',
    measurementId: 'G-EGEW0RSKS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc4dSlxr6A7JqwcWhiTcxIM-TCm8D5vMM',
    appId: '1:430839867495:android:aaeca00c8e22c74a0e4cc2',
    messagingSenderId: '430839867495',
    projectId: 'push-notifications-v1-dec26',
    storageBucket: 'push-notifications-v1-dec26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs9MEaDIntK-jqfJ_umbIrD_Bcm_kWH7g',
    appId: '1:430839867495:ios:8162dddb8ab801050e4cc2',
    messagingSenderId: '430839867495',
    projectId: 'push-notifications-v1-dec26',
    storageBucket: 'push-notifications-v1-dec26.appspot.com',
    iosClientId: '430839867495-b8d2fh5dvs6rinrus7sf8l3ut828kl65.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationsV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs9MEaDIntK-jqfJ_umbIrD_Bcm_kWH7g',
    appId: '1:430839867495:ios:8162dddb8ab801050e4cc2',
    messagingSenderId: '430839867495',
    projectId: 'push-notifications-v1-dec26',
    storageBucket: 'push-notifications-v1-dec26.appspot.com',
    iosClientId: '430839867495-b8d2fh5dvs6rinrus7sf8l3ut828kl65.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationsV1',
  );
}
